import type { Attraction } from "@shared/schema";
import qurumBeachImg from "@/assets/qurum-beach.png";
import mutrahSouqImg from "@/assets/mutrah-souq.png";
import wadiKhoudImg from "@/assets/wadi-khoud.png";
import qurumParkImg from "@/assets/qurum-park.png";
import mutrahFortImg from "@/assets/mutrah-fort.png";
import jebelAkhdarImg from "@/assets/jebel-akhdar.png";
import nizwaFortImg from "@/assets/nizwa-fort.png";
import wadiGhoulImg from "@/assets/wadi-ghoul.png";
import nizwaSouqImg from "@/assets/nizwa-souq.png";
import nizwaParkImg from "@/assets/nizwa-park.png";
import barHikmanImg from "@/assets/bar-hikman.png";
import soharFortImg from "@/assets/sohar-fort.png";
import jubileeParkImg from "@/assets/jubilee-park.png";
import soharMallImg from "@/assets/sohar-mall.png";
import soharBeachImg from "@/assets/sohar-beach.png";
import wadiDarbatImg from "@/assets/wadi-darbat.png";
import salalahMallImg from "@/assets/salalah-grand-mall.png";
import alBaleedParkImg from "@/assets/al-baleed-park.png";
import souqAlHaffaImg from "@/assets/souq-al-haffa.png";
import mughsailBeachImg from "@/assets/mughsail-beach.png";
import alHadabiComplexImg from "@/assets/al-hadabi-complex.png";
import rustaqFortImg from "@/assets/rustaq-fort.png";
import ainAlKasfaImg from "@/assets/ain-al-kasfa.png";
import rustaqSouqImg from "@/assets/rustaq-souq.png";
import wadiHoqainImg from "@/assets/wadi-hoqain.png";
import khairanBoatsImg from "@/assets/khairan-boats.png";
import khorShamImg from "@/assets/khor-sham.png";
import khasabFortImg from "@/assets/khasab-fort.png";
import wadiKhabShamsiImg from "@/assets/wadi-khab-shamsi.png";
import buraimiMallImg from "@/assets/buraimi-mall.png";
import saaraOasisImg from "@/assets/saara-oasis.png";
import buraimiParkImg from "@/assets/buraimi-park.png";
import hisnKhandaqImg from "@/assets/hisn-khandaq.png";
import wadiHayoolImg from "@/assets/wadi-hayool.png";

const imageMap: Record<string, string> = {};

export function getAttractionImage(imagePath: string): string {
  return imageMap[imagePath] || imagePath;
}

export const governorates = [
  { id: "muscat", nameAr: "محافظة مسقط" },
  { id: "dakhiliyah", nameAr: "محافظة الداخلية" },
  { id: "wusta", nameAr: "محافظة الوسطى" },
  { id: "dhofar", nameAr: "محافظة ظفار" },
  { id: "north_batinah", nameAr: "محافظة شمال الباطنة" },
  { id: "south_batinah", nameAr: "محافظة جنوب الباطنة" },
  { id: "north_sharqiyah", nameAr: "محافظة شمال الشرقية" },
  { id: "south_sharqiyah", nameAr: "محافظة جنوب الشرقية" },
  { id: "dhahirah", nameAr: "محافظة الظاهرة" },
  { id: "musandam", nameAr: "محافظة مسندم" },
  { id: "buraimi", nameAr: "محافظة البريمي" },
];

export const categories = [
  { id: "markets", nameAr: "الأسواق التجارية" },
  { id: "entertainment", nameAr: "الأماكن الترفيهية" },
  { id: "heritage", nameAr: "الأماكن التراثية" },
  { id: "nature", nameAr: "الأماكن الطبيعية" },
  { id: "wadis", nameAr: "الأودية" },
  { id: "springs", nameAr: "العيون الطبيعية" },
];

export const wilayatsByGovernorate: Record<string, string[]> = {
  muscat: ["ولاية مسقط", "ولاية مطرح", "ولاية بوشر", "ولاية السيب", "ولاية العامرات", "ولاية قريات"],
  dakhiliyah: ["ولاية نزوى", "ولاية بهلاء", "ولاية منح", "ولاية سمائل", "ولاية إزكي", "ولاية ادم", "ولاية الحمراء", "ولاية الجبل الاخضر"],
  wusta: ["ولاية محوت", "ولاية هيما", "ولاية الجازر", "ولاية الدقم"],
  dhofar: ["ولاية صلالة", "ولاية طاقة", "ولاية مرباط", "ولاية سدح", "ولاية رخيوت", "ولاية ضلكوت", "ولاية المزيونة", "ولاية شليم وجزر الحلانيات", "ولاية ثمريت", "ولاية مقشن"],
  north_batinah: ["ولاية صحار", "ولاية شناص", "ولاية لوى", "ولاية صحم", "ولاية الخابورة", "ولاية السويق"],
  south_batinah: ["ولاية الرستاق", "ولاية العوابي", "ولاية نخل", "ولاية وادي المعاول", "ولاية بركاء", "ولاية المصنعة"],
  north_sharqiyah: ["ولاية إبراء", "ولاية المضيبي", "ولاية بدية", "ولاية القابل", "ولاية وادي بني خالد", "ولاية دماء والطائيين"],
  south_sharqiyah: ["ولاية صور", "ولاية الكامل والوافي", "ولاية جعلان بني بو حسن", "ولاية جعلان بني بو علي", "ولاية مصيرة"],
  dhahirah: ["ولاية عبري", "ولاية ينقل", "ولاية ضنك"],
  musandam: ["ولاية خصب", "ولاية بخا", "ولاية دبا", "ولاية مدحا"],
  buraimi: ["ولاية البريمي", "ولاية محضة", "ولاية السنينة"],
};

export const attractions: Attraction[] = [
  {
    id: "1",
    name: "شاطئ القرم",
    nameAr: "شاطئ القرم",
    description: "من الشواطئ الرملية التي تجذب العائلات للتنزه على الشاطئ والاستمتاع بالأجواء البحرية الهادئة.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية بوشر",
    category: "nature",
    image: qurumBeachImg,
    mapUrl: "https://maps.app.goo.gl/4YyuXLLuBvA9qLXG9",
    rating: "4.5",
    lat: 23.6071,
    lng: 58.4942
  },
  {
    id: "2",
    name: "سوق مطرح",
    nameAr: "سوق مطرح",
    description: "أحد أقدم وأشهر الأسواق العُمانية. يضم المتاجر التي تبيع المصنوعات الحرفية العُمانية كالخناجر والنحاسيات والبخور والعطور التقليدية.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية مطرح",
    category: "markets",
    image: mutrahSouqImg,
    mapUrl: "https://maps.app.goo.gl/qJGC5Rk4sqosFNyB8",
    rating: "4.8",
    lat: 23.6193,
    lng: 58.5713
  },
  {
    id: "3",
    name: "وادي الخوض",
    nameAr: "وادي الخوض",
    description: "وادٍ طبيعي جميل يتكوّن من برك مائية وعيون مياه ثابتة. مكان مثالي للاسترخاء والتمتع بالطبيعة.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية السيب",
    category: "wadis",
    image: wadiKhoudImg,
    mapUrl: "https://maps.app.goo.gl/zWP2ztmNNAz6CB7y5",
    rating: "4.3",
    lat: 23.5451,
    lng: 58.0872
  },
  {
    id: "4",
    name: "منتزه القرم الطبيعي",
    nameAr: "منتزه القرم الطبيعي",
    description: "أكبر حديقة عامة في مسقط. يجمع بين المناظر الخضراء الشاسعة والهندسة المعمارية الجمالية. مكان مثالي للعائلات.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية بوشر",
    category: "entertainment",
    image: qurumParkImg,
    mapUrl: "https://maps.app.goo.gl/8in1t2GTgnyJxLjA9",
    rating: "4.7",
    lat: 23.5992,
    lng: 58.4156
  },
  {
    id: "5",
    name: "قلعة مطرح",
    nameAr: "قلعة مطرح",
    description: "قلعة تاريخية تراثية تقع على تلال جبال الحجر المطلة على ميناء السلطان قابوس. تعكس التاريخ العريق لسلطنة عُمان.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية مطرح",
    category: "heritage",
    image: mutrahFortImg,
    mapUrl: "https://maps.app.goo.gl/NNR1WgRHypcg5Fst7",
    rating: "4.5",
    lat: 23.6225,
    lng: 58.5695
  },
  {
    id: "6",
    name: "جبل الأخضر",
    nameAr: "جبل الأخضر",
    description: "أعلى جبل في محافظة الداخلية. يتميّز بجوه المعتدل وطبيعته الخضراء وثماره المميزة كالرمان والورد.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية الجبل الاخضر",
    category: "nature",
    image: jebelAkhdarImg,
    mapUrl: "https://maps.app.goo.gl/ZpensdHeBvouYugX8",
    rating: "4.9",
    lat: 23.0742,
    lng: 57.6517
  },
  {
    id: "7",
    name: "قلعة نزوى",
    nameAr: "قلعة نزوى",
    description: "حصن تاريخي ضخم في مركز مدينة نزوى. يتوسط سوق نزوى التقليدي الشعبي المعروف بصناعاته الحرفية.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية نزوى",
    category: "heritage",
    image: nizwaFortImg,
    mapUrl: "https://maps.app.goo.gl/sjaLFYq4BFUtcmqU6",
    rating: "4.8",
    lat: 22.9320,
    lng: 57.5292
  },
  {
    id: "8",
    name: "وادي الغول",
    nameAr: "وادي الغول",
    description: "أحد أجمل المعالم الطبيعية في الداخلية. يمتاز بمناظره الخلابة وضخامة تضاريسه الجبلية.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية الحمراء",
    category: "wadis",
    image: wadiGhoulImg,
    mapUrl: "https://maps.app.goo.gl/Ch5n2k9sDgediE4p7",
    rating: "4.7",
    lat: 23.1250,
    lng: 57.3500
  },
  {
    id: "9",
    name: "سوق نزوى التقليدي",
    nameAr: "سوق نزوى التقليدي",
    description: "سوق شعبي تاريخي، يمتاز بمحلاته الشعبية والصناعات الحرفية التقليدية العُمانية.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية نزوى",
    category: "markets",
    image: nizwaSouqImg,
    mapUrl: "https://maps.app.goo.gl/HmAB16MB7HbAdNuTA",
    rating: "4.6",
    lat: 22.9315,
    lng: 57.5283
  },
  {
    id: "10",
    name: "حديقة فلج دارس",
    nameAr: "حديقة فلج دارس",
    description: "متنزه حضري حديث في قلب نزوى. يحتوي على بحيرة اصطناعية ومسرح مفتوح ومناطق ألعاب للأطفال.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية نزوى",
    category: "entertainment",
    image: nizwaParkImg,
    mapUrl: "https://maps.app.goo.gl/jotwJS8znZYBznfW7",
    rating: "4.4",
    lat: 22.9251,
    lng: 57.5350
  },
  {
    id: "11",
    name: "شاطئ بر الحكمان",
    nameAr: "شاطئ بر الحكمان",
    description: "شاطئ بر الحكمان امتداد طبيعي فريد. مناسب للعائلات والتخييم والمغامرات البحرية.",
    governorate: "محافظة الوسطى",
    governorateId: "wusta",
    wilayat: "ولاية محوت",
    category: "nature",
    image: barHikmanImg,
    mapUrl: "https://maps.app.goo.gl/EmekuatAbuASqSaXA",
    rating: "4.6",
    lat: 20.2670,
    lng: 58.4100
  },
  {
    id: "12",
    name: "عين بوي الحوجاء",
    nameAr: "عين بوي الحوجاء",
    description: "واحدة من ثلاث عيون طبيعية مشهورة في هيما. تتشكل العين فوق صخرة ضخمة لهبّة تشبه المظلة الطبيعية، تنبع منها مياه دائمة نقية.",
    governorate: "محافظة الوسطى",
    governorateId: "wusta",
    wilayat: "ولاية هيما",
    category: "springs",
    image: "",
    mapUrl: null,
    rating: "4.5",
    lat: 19.9500,
    lng: 56.2800
  },
  {
    id: "13",
    name: "صحار سيتي سنتر",
    nameAr: "صحار سيتي سنتر",
    description: "أفضل مول في صحار، يضم أشهر العلامات التجارية والمطاعم ومرافق الترفيه للعائلات.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "entertainment",
    image: soharMallImg,
    mapUrl: null,
    rating: "4.3",
    lat: 24.3650,
    lng: 56.7420
  },
  {
    id: "14",
    name: "قلعة صحار",
    nameAr: "قلعة صحار",
    description: "قلعة تاريخية تضم متاحف تحكي تاريخ المدينة العريق والتراث البحري القديم لصحار.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "heritage",
    image: soharFortImg,
    mapUrl: null,
    rating: "4.7",
    lat: 24.3472,
    lng: 56.7459
  },
  {
    id: "15",
    name: "سوق صحار التاريخي",
    nameAr: "سوق صحار التاريخي",
    description: "سوق تجاري بني على الطراز الإسلامي التقليدي ويقع بالقرب من القلعة، يعرض المنتجات التقليدية والحرفية.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "16",
    name: "شاطئ صحار",
    nameAr: "شاطئ صحار",
    description: "شاطئ ممتاز للمشي والجلوس وقت الغروب، يوفر إطلالات خلابة على البحر.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "nature",
    image: soharBeachImg,
    mapUrl: null,
    rating: "4.4"
  },
  {
    id: "17",
    name: "وادي الجزي",
    nameAr: "وادي الجزي",
    description: "وادٍ طبيعي جميل في صحار، يتميز بمناظره الخلابة ومياهه الجارية.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "18",
    name: "حديقة اليوبيل الفضي",
    nameAr: "حديقة اليوبيل الفضي",
    description: "حديقة عامة جميلة في صحار، مثالية للتنزه والاسترخاء مع العائلة.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "entertainment",
    image: jubileeParkImg,
    mapUrl: null,
    rating: "4.3"
  },
  {
    id: "19",
    name: "صلالة كاردنز مول",
    nameAr: "صلالة كاردنز مول",
    description: "أفضل مول في صلالة، يتميز بتصميم معماري جميل يدمج بين الحداثة والتراث مع مرافق تسوق وترفيه متنوعة.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "entertainment",
    image: salalahMallImg,
    mapUrl: null,
    rating: "4.5",
    lat: 17.0203,
    lng: 54.0910
  },
  {
    id: "20",
    name: "منتزه البليد الأثري",
    nameAr: "منتزه البليد الأثري",
    description: "موقع أثري مسجل في اليونسكو ويضم متحف أرض اللبان. يروي تاريخ تجارة اللبان العريق في ظفار.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "heritage",
    image: alBaleedParkImg,
    mapUrl: null,
    rating: "4.8",
    lat: 17.0090,
    lng: 54.1250
  },
  {
    id: "21",
    name: "سوق الحافة",
    nameAr: "سوق الحافة",
    description: "السوق التقليدي الأشهر في صلالة لبيع اللبان والبخور والمنسوجات والمنتجات التقليدية.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "markets",
    image: souqAlHaffaImg,
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "22",
    name: "شلالات وادي دربات",
    nameAr: "شلالات وادي دربات",
    description: "وادٍ طبيعي خلاب يضم شلالات مائية رائعة، خاصة في موسم الخريف حيث تتدفق المياه بغزارة.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "wadis",
    image: wadiDarbatImg,
    mapUrl: null,
    rating: "4.9",
    lat: 17.1150,
    lng: 54.4370
  },
  {
    id: "23",
    name: "سهل أتين",
    nameAr: "سهل أتين",
    description: "سهل أخضر طبيعي ساحر، يتميز بمناظره الخلابة خاصة في موسم الخريف.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "24",
    name: "عين جرزيز",
    nameAr: "عين جرزيز",
    description: "عين طبيعية جميلة تتدفق منها المياه العذبة، محاطة بالخضرة والطبيعة الساحرة.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "springs",
    image: "",
    mapUrl: null,
    rating: "4.6",
    lat: 17.1070,
    lng: 54.0680
  },
  {
    id: "25",
    name: "نافورة المغسيل",
    nameAr: "نافورة المغسيل",
    description: "ظاهرة طبيعية فريدة حيث تندفع المياه من الصخور بشكل مذهل، من أشهر المعالم السياحية في صلالة.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "nature",
    image: mughsailBeachImg,
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "26",
    name: "مجمع الواحة",
    nameAr: "مجمع الواحة",
    description: "مجمع تجاري في الرستاق يوفر مرافق تسوق وخدمات متنوعة للزوار.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.0"
  },
  {
    id: "27",
    name: "قلعة الرستاق",
    nameAr: "قلعة الرستاق",
    description: "قلعة تاريخية ضخمة تعد من أهم المعالم التراثية في عُمان، تروي تاريخ المنطقة العريق.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "heritage",
    image: rustaqFortImg,
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "28",
    name: "حصن الحزم",
    nameAr: "حصن الحزم",
    description: "تحفة معمارية دفاعية فريدة، يعتبر من أهم الحصون في سلطنة عُمان بتصميمه الهندسي المتقن.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "29",
    name: "سوق الرستاق القديم",
    nameAr: "سوق الرستاق القديم",
    description: "سوق تقليدي حيوي خاصة في الصباح الباكر، مشهور ببيع العسل والتمور والمنتجات المحلية.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "markets",
    image: rustaqSouqImg,
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "30",
    name: "عين الكسفة",
    nameAr: "عين الكسفة",
    description: "عين مياه طبيعية حارة تصل حرارتها لـ 45 درجة مئوية، لها فوائد علاجية ويقصدها الزوار للاستشفاء.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "springs",
    image: ainAlKasfaImg,
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "31",
    name: "وادي الحوقين",
    nameAr: "وادي الحوقين",
    description: "وادٍ طبيعي ساحر يضم شلالات مياه دائمة الجريان وسط النخيل، من أجمل الأودية في عُمان.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "wadis",
    image: wadiHoqainImg,
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "32",
    name: "سوق عبري",
    nameAr: "سوق عبري",
    description: "سوق تقليدي في ولاية عبري، يعرض المنتجات المحلية والحرف التقليدية.",
    governorate: "محافظة الظاهرة",
    governorateId: "dhahirah",
    wilayat: "ولاية عبري",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.4"
  },
  {
    id: "33",
    name: "مهرجان الظاهرة السياحي",
    nameAr: "مهرجان الظاهرة السياحي",
    description: "مهرجان سياحي سنوي يقام في محافظة الظاهرة، يضم فعاليات ثقافية وترفيهية متنوعة.",
    governorate: "محافظة الظاهرة",
    governorateId: "dhahirah",
    wilayat: "ولاية عبري",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "34",
    name: "مسفاة العبريين",
    nameAr: "مسفاة العبريين",
    description: "قرية جبلية تراثية ذات طبيعة خلابة، تتميز بمدرجاتها الزراعية ومنازلها التقليدية.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية الحمراء",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "35",
    name: "سد المحيول",
    nameAr: "سد المحيول",
    description: "سد تراثي قديم يعكس براعة الهندسة العُمانية التقليدية في إدارة المياه.",
    governorate: "محافظة الظاهرة",
    governorateId: "dhahirah",
    wilayat: "ولاية عبري",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.3"
  },
  {
    id: "36",
    name: "وادي ضم",
    nameAr: "وادي ضم",
    description: "وادٍ طبيعي جميل في محافظة الظاهرة، يتميز بمناظره الخلابة ومياهه الجارية.",
    governorate: "محافظة الظاهرة",
    governorateId: "dhahirah",
    wilayat: "ولاية ضنك",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "37",
    name: "سوق صور القديم",
    nameAr: "سوق صور القديم",
    description: "سوق تقليدي عريق في ولاية صور، يعرض المنتجات البحرية والحرف التقليدية.",
    governorate: "محافظة جنوب الشرقية",
    governorateId: "south_sharqiyah",
    wilayat: "ولاية صور",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.4"
  },
  {
    id: "38",
    name: "مرح لاند",
    nameAr: "مرح لاند",
    description: "مدينة ترفيهية للعائلات تضم ألعاب متنوعة ومرافق ترفيهية للأطفال والكبار.",
    governorate: "محافظة جنوب الشرقية",
    governorateId: "south_sharqiyah",
    wilayat: "ولاية صور",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.3"
  },
  {
    id: "39",
    name: "شاطئ الأشخرة",
    nameAr: "شاطئ الأشخرة",
    description: "شاطئ طبيعي ساحر يتميز برماله الذهبية ومياهه الصافية، مثالي للسباحة والتخييم.",
    governorate: "محافظة جنوب الشرقية",
    governorateId: "south_sharqiyah",
    wilayat: "ولاية جعلان بني بو علي",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "40",
    name: "حصن بلاد صور",
    nameAr: "حصن بلاد صور",
    description: "حصن تراثي تاريخي يعكس التاريخ البحري العريق لولاية صور وصناعة السفن.",
    governorate: "محافظة جنوب الشرقية",
    governorateId: "south_sharqiyah",
    wilayat: "ولاية صور",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "41",
    name: "وادي حاور",
    nameAr: "وادي حاور",
    description: "وادٍ طبيعي جميل في جنوب الشرقية، يتميز بمناظره الخلابة وبركه المائية.",
    governorate: "محافظة جنوب الشرقية",
    governorateId: "south_sharqiyah",
    wilayat: "ولاية جعلان بني بو علي",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "42",
    name: "سوق إبراء",
    nameAr: "سوق إبراء",
    description: "سوق تقليدي عريق في ولاية إبراء، يضم محلات الحرف اليدوية والمنتجات المحلية.",
    governorate: "محافظة شمال الشرقية",
    governorateId: "north_sharqiyah",
    wilayat: "ولاية إبراء",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "43",
    name: "رمال وهيبة",
    nameAr: "رمال وهيبة",
    description: "صحراء رملية ذهبية مذهلة تمتد على مساحات واسعة، مثالية للتخييم ورحلات السفاري.",
    governorate: "محافظة شمال الشرقية",
    governorateId: "north_sharqiyah",
    wilayat: "ولاية بدية",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "44",
    name: "وادي تيوي",
    nameAr: "وادي تيوي",
    description: "وادٍ خلاب يتميز بقراه الجبلية المعلقة ومزارع النخيل ومياهه الجارية.",
    governorate: "محافظة شمال الشرقية",
    governorateId: "north_sharqiyah",
    wilayat: "ولاية صور",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "45",
    name: "بيت الدّرْوازة",
    nameAr: "بيت الدّرْوازة",
    description: "منزل تراثي تاريخي يعكس العمارة العمانية التقليدية وأسلوب الحياة القديم.",
    governorate: "محافظة شمال الشرقية",
    governorateId: "north_sharqiyah",
    wilayat: "ولاية إبراء",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "46",
    name: "وادي بني خالد",
    nameAr: "وادي بني خالد",
    description: "أشهر الأودية في عُمان، يتميز ببركه الفيروزية الصافية وكهوفه الطبيعية.",
    governorate: "محافظة شمال الشرقية",
    governorateId: "north_sharqiyah",
    wilayat: "ولاية بني خالد",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.9"
  },
  {
    id: "47",
    name: "مركز زاد المدينة للتسوق",
    nameAr: "مركز زاد المدينة للتسوق",
    description: "مركز تسوق وسوبرماركت في ولاية خصب، يوفر خيارات متنوعة من البضائع الأساسية والاحتياجات اليومية في بيئة نظيفة ومنظمة.",
    governorate: "محافظة مسندم",
    governorateId: "musandam",
    wilayat: "ولاية خصب",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.3"
  },
  {
    id: "48",
    name: "الرحلات البحرية في الخيران",
    nameAr: "الرحلات البحرية في الخيران",
    description: "جولات ممتعة بالقوارب التقليدية (الدهو) عبر الأخوار والجبال البحرية الخلابة، حيث يمكنك مشاهدة الدلافين والسباحة والغطس حول الجزر واستكشاف القرى الساحلية القديمة.",
    governorate: "محافظة مسندم",
    governorateId: "musandam",
    wilayat: "ولاية خصب",
    category: "entertainment",
    image: khairanBoatsImg,
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "49",
    name: "خور شم",
    nameAr: "خور شم",
    description: "من أجمل الأخوار الطبيعية، يتميز بمياهه الفيروزية الهادئة المحاطة بالجبال الشاهقة، وجهة مثالية لرحلات القوارب ومشاهدة الحياة البحرية.",
    governorate: "محافظة مسندم",
    governorateId: "musandam",
    wilayat: "ولاية خصب",
    category: "nature",
    image: khorShamImg,
    mapUrl: null,
    rating: "4.9"
  },
  {
    id: "50",
    name: "قلعة خصب",
    nameAr: "قلعة خصب",
    description: "معلم تاريخي بارز يعود للقرن السابع عشر، تتميز بأبراجها الحجرية وأسوارها التي تعكس الطابع المعماري العُماني التقليدي، وتضم متحفًا يعرض تراث المنطقة.",
    governorate: "محافظة مسندم",
    governorateId: "musandam",
    wilayat: "ولاية خصب",
    category: "heritage",
    image: khasabFortImg,
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "51",
    name: "وادي خب الشماسي",
    nameAr: "وادي خب الشماسي",
    description: "وادٍ يتميز بطبيعته الجبلية الخلابة وممراته الصخرية التي تتخللها برك مياه موسمية، وجهة مثالية لمحبي المغامرة والتنزه.",
    governorate: "محافظة مسندم",
    governorateId: "musandam",
    wilayat: "ولاية دبا",
    category: "wadis",
    image: wadiKhabShamsiImg,
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "52",
    name: "البريمي مول",
    nameAr: "البريمي مول",
    description: "مركز تسوق محلي يجمع تحت سقف واحد مجموعة من المتاجر ومتاجر الأزياء والسلع المختلفة، وجهة مناسبة للتسوق وقضاء وقت مع العائلة.",
    governorate: "محافظة البريمي",
    governorateId: "buraimi",
    wilayat: "ولاية البريمي",
    category: "markets",
    image: buraimiMallImg,
    mapUrl: null,
    rating: "4.2"
  },
  {
    id: "53",
    name: "حديقة البريمي العامة",
    nameAr: "حديقة البريمي العامة",
    description: "حديقة واسعة توفر مكانًا مثاليًا للعائلات للاسترخاء والتنزه، تتميز بمنتزهات وألعاب للأطفال ومسارات للمشي وفعاليات ثقافية وترفيهية.",
    governorate: "محافظة البريمي",
    governorateId: "buraimi",
    wilayat: "ولاية البريمي",
    category: "entertainment",
    image: buraimiParkImg,
    mapUrl: null,
    rating: "4.4"
  },
  {
    id: "54",
    name: "واحة صعراء",
    nameAr: "واحة صعراء",
    description: "منطقة طبيعية خضراء تضم أشجار النخيل والنباتات المثمرة كالمانجو والليمون، مكان مفضل للتنزّه والاسترخاء وسط الطبيعة.",
    governorate: "محافظة البريمي",
    governorateId: "buraimi",
    wilayat: "ولاية البريمي",
    category: "nature",
    image: saaraOasisImg,
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "55",
    name: "حصن الخندق",
    nameAr: "حصن الخندق",
    description: "معلم تاريخي قديم يعكس الطابع المعماري العُماني التقليدي، بني للحماية والدفاع عن المدينة، يتميز بأسواره وأبراج المراقبة.",
    governorate: "محافظة البريمي",
    governorateId: "buraimi",
    wilayat: "ولاية البريمي",
    category: "heritage",
    image: hisnKhandaqImg,
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "51",
    name: "مجمع الهدابي",
    nameAr: "مجمع الهدابي",
    description: "مجمع تجاري متنوع في صلالة يضم محلات تجارية ومطاعم وخدمات متعددة للزوار.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "entertainment",
    image: alHadabiComplexImg,
    mapUrl: null,
    rating: "4.2",
    lat: 17.0180,
    lng: 54.0850
  },
  {
    id: "56",
    name: "وادي الحيول",
    nameAr: "وادي الحيول",
    description: "وادٍ طبيعي خلاب محاط بالجبال الشاهقة، يتميز بمناظره الطبيعية الساحرة والنخيل الأخضر وسط الجبال الصخرية.",
    governorate: "محافظة البريمي",
    governorateId: "buraimi",
    wilayat: "ولاية البريمي",
    category: "wadis",
    image: wadiHayoolImg,
    mapUrl: null,
    rating: "4.6"
  }
];
