import type { Attraction } from "@shared/schema";

const imageMap: Record<string, string> = {};

export function getAttractionImage(imagePath: string): string {
  return imageMap[imagePath] || imagePath;
}

export const governorates = [
  { id: "muscat", nameAr: "محافظة مسقط" },
  { id: "dakhiliyah", nameAr: "محافظة الداخلية" },
  { id: "wusta", nameAr: "محافظة الوسطى" },
  { id: "dhofar", nameAr: "محافظة ظفار" },
  { id: "north_batinah", nameAr: "محافظة شمال الباطنة" },
  { id: "south_batinah", nameAr: "محافظة جنوب الباطنة" },
  { id: "north_sharqiyah", nameAr: "محافظة شمال الشرقية" },
  { id: "south_sharqiyah", nameAr: "محافظة جنوب الشرقية" },
  { id: "dhahirah", nameAr: "محافظة الظاهرة" },
  { id: "musandam", nameAr: "محافظة مسندم" },
  { id: "buraimi", nameAr: "محافظة البريمي" },
];

export const categories = [
  { id: "markets", nameAr: "الأسواق التجارية" },
  { id: "entertainment", nameAr: "الأماكن الترفيهية" },
  { id: "heritage", nameAr: "الأماكن التراثية" },
  { id: "nature", nameAr: "الأماكن الطبيعية" },
  { id: "wadis", nameAr: "الأودية" },
  { id: "springs", nameAr: "العيون الطبيعية" },
];

export const wilayatsByGovernorate: Record<string, string[]> = {
  muscat: ["ولاية مسقط", "ولاية مطرح", "ولاية بوشر", "ولاية السيب", "ولاية العامرات", "ولاية قريات"],
  dakhiliyah: ["ولاية نزوى", "ولاية بهلاء", "ولاية منح", "ولاية سمائل", "ولاية إزكي", "ولاية ادم", "ولاية الحمراء", "ولاية الجبل الاخضر"],
  wusta: ["ولاية محوت", "ولاية هيما", "ولاية الجازر", "ولاية الدقم"],
  dhofar: ["ولاية صلالة", "ولاية طاقة", "ولاية مرباط", "ولاية سدح", "ولاية رخيوت", "ولاية ضلكوت", "ولاية المزيونة", "ولاية شليم وجزر الحلانيات", "ولاية ثمريت", "ولاية مقشن"],
  north_batinah: ["ولاية صحار", "ولاية شناص", "ولاية لوى", "ولاية صحم", "ولاية الخابورة", "ولاية السويق"],
  south_batinah: ["ولاية الرستاق", "ولاية العوابي", "ولاية نخل", "ولاية وادي المعاول", "ولاية بركاء", "ولاية المصنعة"],
  north_sharqiyah: ["ولاية إبراء", "ولاية المضيبي", "ولاية بدية", "ولاية القابل", "ولاية وادي بني خالد", "ولاية دماء والطائيين"],
  south_sharqiyah: ["ولاية صور", "ولاية الكامل والوافي", "ولاية جعلان بني بو حسن", "ولاية جعلان بني بو علي", "ولاية مصيرة"],
  dhahirah: ["ولاية عبري", "ولاية ينقل", "ولاية ضنك"],
  musandam: ["ولاية خصب", "ولاية بخا", "ولاية دبا", "ولاية مدحا"],
  buraimi: ["ولاية البريمي", "ولاية محضة", "ولاية السنينة"],
};

export const attractions: Attraction[] = [
  {
    id: "1",
    name: "شاطئ القرم",
    nameAr: "شاطئ القرم",
    description: "من الشواطئ الرملية التي تجذب العائلات للتنزه على الشاطئ والاستمتاع بالأجواء البحرية الهادئة.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية بوشر",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "2",
    name: "سوق مطرح",
    nameAr: "سوق مطرح",
    description: "أحد أقدم وأشهر الأسواق العُمانية. يضم المتاجر التي تبيع المصنوعات الحرفية العُمانية كالخناجر والنحاسيات والبخور والعطور التقليدية.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية مطرح",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "3",
    name: "وادي الخوض",
    nameAr: "وادي الخوض",
    description: "وادٍ طبيعي جميل يتكوّن من برك مائية وعيون مياه ثابتة. مكان مثالي للاسترخاء والتمتع بالطبيعة.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية السيب",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.3"
  },
  {
    id: "4",
    name: "منتزه القرم الطبيعي",
    nameAr: "منتزه القرم الطبيعي",
    description: "أكبر حديقة عامة في مسقط. يجمع بين المناظر الخضراء الشاسعة والهندسة المعمارية الجمالية. مكان مثالي للعائلات.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية بوشر",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "5",
    name: "قلعة مطرح",
    nameAr: "قلعة مطرح",
    description: "قلعة تاريخية تراثية تقع على تلال جبال الحجر المطلة على ميناء السلطان قابوس. تعكس التاريخ العريق لسلطنة عُمان.",
    governorate: "محافظة مسقط",
    governorateId: "muscat",
    wilayat: "ولاية مطرح",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "6",
    name: "جبل الأخضر",
    nameAr: "جبل الأخضر",
    description: "أعلى جبل في محافظة الداخلية. يتميّز بجوه المعتدل وطبيعته الخضراء وثماره المميزة كالرمان والورد.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية الجبل الاخضر",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.9"
  },
  {
    id: "7",
    name: "قلعة نزوى",
    nameAr: "قلعة نزوى",
    description: "حصن تاريخي ضخم في مركز مدينة نزوى. يتوسط سوق نزوى التقليدي الشعبي المعروف بصناعاته الحرفية.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية نزوى",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "8",
    name: "وادي الغول",
    nameAr: "وادي الغول",
    description: "أحد أجمل المعالم الطبيعية في الداخلية. يمتاز بمناظره الخلابة وضخامة تضاريسه الجبلية.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية الحمراء",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "9",
    name: "سوق نزوى التقليدي",
    nameAr: "سوق نزوى التقليدي",
    description: "سوق شعبي تاريخي، يمتاز بمحلاته الشعبية والصناعات الحرفية التقليدية العُمانية.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية نزوى",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "10",
    name: "حديقة نزوى العامة",
    nameAr: "حديقة نزوى العامة",
    description: "متنزه حضري حديث في قلب نزوى. يحتوي على بحيرة اصطناعية ومسرح مفتوح ومناطق ألعاب للأطفال.",
    governorate: "محافظة الداخلية",
    governorateId: "dakhiliyah",
    wilayat: "ولاية نزوى",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.4"
  },
  {
    id: "11",
    name: "شاطئ بر الحكمان",
    nameAr: "شاطئ بر الحكمان",
    description: "شاطئ بر الحكمان امتداد طبيعي فريد. مناسب للعائلات والتخييم والمغامرات البحرية.",
    governorate: "محافظة الوسطى",
    governorateId: "wusta",
    wilayat: "ولاية محوت",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "12",
    name: "عين بوي الحوجاء",
    nameAr: "عين بوي الحوجاء",
    description: "واحدة من ثلاث عيون طبيعية مشهورة في هيما. تتشكل العين فوق صخرة ضخمة لهبّة تشبه المظلة الطبيعية، تنبع منها مياه دائمة نقية.",
    governorate: "محافظة الوسطى",
    governorateId: "wusta",
    wilayat: "ولاية هيما",
    category: "springs",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "13",
    name: "صحار سيتي سنتر",
    nameAr: "صحار سيتي سنتر",
    description: "أفضل مول في صحار، يضم أشهر العلامات التجارية والمطاعم ومرافق الترفيه للعائلات.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.3"
  },
  {
    id: "14",
    name: "قلعة صحار",
    nameAr: "قلعة صحار",
    description: "قلعة تاريخية تضم متاحف تحكي تاريخ المدينة العريق والتراث البحري القديم لصحار.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "15",
    name: "سوق صحار التاريخي",
    nameAr: "سوق صحار التاريخي",
    description: "سوق تجاري بني على الطراز الإسلامي التقليدي ويقع بالقرب من القلعة، يعرض المنتجات التقليدية والحرفية.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "16",
    name: "شاطئ صحار",
    nameAr: "شاطئ صحار",
    description: "شاطئ ممتاز للمشي والجلوس وقت الغروب، يوفر إطلالات خلابة على البحر.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.4"
  },
  {
    id: "17",
    name: "وادي الجزي",
    nameAr: "وادي الجزي",
    description: "وادٍ طبيعي جميل في صحار، يتميز بمناظره الخلابة ومياهه الجارية.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "18",
    name: "حديقة اليوبيل الفضي",
    nameAr: "حديقة اليوبيل الفضي",
    description: "حديقة عامة جميلة في صحار، مثالية للتنزه والاسترخاء مع العائلة.",
    governorate: "محافظة شمال الباطنة",
    governorateId: "north_batinah",
    wilayat: "ولاية صحار",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.3"
  },
  {
    id: "19",
    name: "صلالة كاردنز مول",
    nameAr: "صلالة كاردنز مول",
    description: "أفضل مول في صلالة، يتميز بتصميم معماري جميل يدمج بين الحداثة والتراث مع مرافق تسوق وترفيه متنوعة.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "20",
    name: "منتزه البليد الأثري",
    nameAr: "منتزه البليد الأثري",
    description: "موقع أثري مسجل في اليونسكو ويضم متحف أرض اللبان. يروي تاريخ تجارة اللبان العريق في ظفار.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "21",
    name: "سوق الحافة",
    nameAr: "سوق الحافة",
    description: "السوق التقليدي الأشهر في صلالة لبيع اللبان والبخور والمنسوجات والمنتجات التقليدية.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "22",
    name: "شلالات وادي دربات",
    nameAr: "شلالات وادي دربات",
    description: "وادٍ طبيعي خلاب يضم شلالات مائية رائعة، خاصة في موسم الخريف حيث تتدفق المياه بغزارة.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.9"
  },
  {
    id: "23",
    name: "سهل أتين",
    nameAr: "سهل أتين",
    description: "سهل أخضر طبيعي ساحر، يتميز بمناظره الخلابة خاصة في موسم الخريف.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "24",
    name: "عين جرزيز",
    nameAr: "عين جرزيز",
    description: "عين طبيعية جميلة تتدفق منها المياه العذبة، محاطة بالخضرة والطبيعة الساحرة.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "springs",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "25",
    name: "نافورة المغسيل",
    nameAr: "نافورة المغسيل",
    description: "ظاهرة طبيعية فريدة حيث تندفع المياه من الصخور بشكل مذهل، من أشهر المعالم السياحية في صلالة.",
    governorate: "محافظة ظفار",
    governorateId: "dhofar",
    wilayat: "ولاية صلالة",
    category: "nature",
    image: "",
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "26",
    name: "مجمع الواحة",
    nameAr: "مجمع الواحة",
    description: "مجمع تجاري في الرستاق يوفر مرافق تسوق وخدمات متنوعة للزوار.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "entertainment",
    image: "",
    mapUrl: null,
    rating: "4.0"
  },
  {
    id: "27",
    name: "قلعة الرستاق",
    nameAr: "قلعة الرستاق",
    description: "قلعة تاريخية ضخمة تعد من أهم المعالم التراثية في عُمان، تروي تاريخ المنطقة العريق.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.7"
  },
  {
    id: "28",
    name: "حصن الحزم",
    nameAr: "حصن الحزم",
    description: "تحفة معمارية دفاعية فريدة، يعتبر من أهم الحصون في سلطنة عُمان بتصميمه الهندسي المتقن.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "heritage",
    image: "",
    mapUrl: null,
    rating: "4.8"
  },
  {
    id: "29",
    name: "سوق الرستاق القديم",
    nameAr: "سوق الرستاق القديم",
    description: "سوق تقليدي حيوي خاصة في الصباح الباكر، مشهور ببيع العسل والتمور والمنتجات المحلية.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "markets",
    image: "",
    mapUrl: null,
    rating: "4.5"
  },
  {
    id: "30",
    name: "عين الكسفة",
    nameAr: "عين الكسفة",
    description: "عين مياه طبيعية حارة تصل حرارتها لـ 45 درجة مئوية، لها فوائد علاجية ويقصدها الزوار للاستشفاء.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "springs",
    image: "",
    mapUrl: null,
    rating: "4.6"
  },
  {
    id: "31",
    name: "وادي الحوقين",
    nameAr: "وادي الحوقين",
    description: "وادٍ طبيعي ساحر يضم شلالات مياه دائمة الجريان وسط النخيل، من أجمل الأودية في عُمان.",
    governorate: "محافظة جنوب الباطنة",
    governorateId: "south_batinah",
    wilayat: "ولاية الرستاق",
    category: "wadis",
    image: "",
    mapUrl: null,
    rating: "4.8"
  }
];
