import type { Hotel } from "@shared/schema";

export const hotels: Hotel[] = [
  {
    id: "1",
    name: "Al Bustan Palace",
    nameAr: "فندق قصر البستان",
    description: "فندق فاخر من فئة الخمس نجوم يقع على شاطئ خاص في مسقط. يتميز بهندسته المعمارية العُمانية الأصيلة وحدائقه الاستوائية الخلابة ومرافقه الراقية.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800",
    ],
    amenities: ["مسبح", "سبا", "شاطئ خاص", "مطاعم", "واي فاي"],
    rating: 4.9,
    pricePerNight: 150,
    stars: 5,
    phone: "+968 2479 9666",
    mapUrl: "https://maps.google.com/?q=23.5728,58.6842",
    roomOptions: [
      {
        id: "1-deluxe",
        name: "Deluxe Room",
        nameAr: "غرفة ديلوكس",
        description: "غرفة أنيقة مع إطلالة على الحديقة، تتميز بديكور عصري ومرافق فاخرة",
        pricePerNight: 150,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة حديقة", "واي فاي", "تلفاز", "ميني بار"],
      },
      {
        id: "1-premier",
        name: "Premier Room",
        nameAr: "غرفة بريميير",
        description: "غرفة واسعة مع إطلالة على البحر وشرفة خاصة",
        pricePerNight: 220,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة بحر", "شرفة خاصة", "واي فاي", "ميني بار", "خدمة الغرف 24 ساعة"],
      },
      {
        id: "1-suite",
        name: "Executive Suite",
        nameAr: "جناح تنفيذي",
        description: "جناح فسيح مع غرفة معيشة منفصلة وإطلالة بانورامية على البحر",
        pricePerNight: 350,
        maxGuests: 3,
        amenities: ["غرفة معيشة", "إطلالة بانورامية", "جاكوزي", "بوتلر خاص", "إفطار مجاني"],
      },
      {
        id: "1-royal",
        name: "Royal Suite",
        nameAr: "الجناح الملكي",
        description: "أفخم أجنحة الفندق مع حمام سباحة خاص وخدمة شخصية متكاملة",
        pricePerNight: 750,
        maxGuests: 4,
        amenities: ["مسبح خاص", "غرفتين نوم", "مطبخ", "بوتلر خاص 24 ساعة", "ليموزين", "سبا خاص"],
      },
    ],
  },
  {
    id: "2",
    name: "Shangri-La Barr Al Jissah",
    nameAr: "شانغريلا بر الجصة",
    description: "منتجع فاخر يضم ثلاثة فنادق على خليج خاص محاط بالجبال. يوفر شواطئ رملية وأنشطة مائية متنوعة ومطاعم عالمية وتجربة استجمام لا تُنسى.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=800",
    ],
    amenities: ["مسبح", "سبا", "شاطئ", "غوص", "مطاعم"],
    rating: 4.8,
    pricePerNight: 200,
    stars: 5,
    phone: "+968 2477 6666",
    roomOptions: [
      {
        id: "2-deluxe",
        name: "Deluxe Room",
        nameAr: "غرفة ديلوكس",
        description: "غرفة أنيقة مع إطلالة على الحديقة، تتميز بديكور عصري ومرافق فاخرة",
        pricePerNight: 200,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة حديقة", "واي فاي", "تلفاز", "ميني بار"],
      },
      {
        id: "2-premier",
        name: "Premier Room",
        nameAr: "غرفة بريميير",
        description: "غرفة واسعة مع إطلالة على البحر وشرفة خاصة",
        pricePerNight: 280,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة بحر", "شرفة خاصة", "واي فاي", "ميني بار", "خدمة الغرف 24 ساعة"],
      },
      {
        id: "2-suite",
        name: "Executive Suite",
        nameAr: "جناح تنفيذي",
        description: "جناح فسيح مع غرفة معيشة منفصلة وإطلالة بانورامية على البحر",
        pricePerNight: 400,
        maxGuests: 3,
        amenities: ["غرفة معيشة", "إطلالة بانورامية", "جاكوزي", "بوتلر خاص", "إفطار مجاني"],
      },
      {
        id: "2-royal",
        name: "Royal Suite",
        nameAr: "الجناح الملكي",
        description: "أفخم أجنحة الفندق مع حمام سباحة خاص وخدمة شخصية متكاملة",
        pricePerNight: 800,
        maxGuests: 4,
        amenities: ["مسبح خاص", "غرفتين نوم", "مطبخ", "بوتلر خاص 24 ساعة", "ليموزين", "سبا خاص"],
      },
    ],
  },
  {
    id: "4",
    name: "W Muscat",
    nameAr: "فندق دبليو مسقط",
    description: "فندق عصري أنيق في قلب مسقط. يجمع بين التصميم الحديث والضيافة العُمانية الأصيلة مع مسبح على السطح وإطلالات على المدينة.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=800",
    ],
    amenities: ["مسبح سطحي", "نادي رياضي", "مطاعم", "بار", "واي فاي"],
    rating: 4.7,
    pricePerNight: 180,
    stars: 5,
    phone: "+968 2494 4444",
    roomOptions: [
      {
        id: "4-deluxe",
        name: "Wonderful Room",
        nameAr: "غرفة وندرفل",
        description: "غرفة عصرية بتصميم جريء مع إطلالة على المدينة",
        pricePerNight: 180,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة مدينة", "واي فاي", "تلفاز", "ميني بار"],
      },
      {
        id: "4-premier",
        name: "Spectacular Room",
        nameAr: "غرفة سبكتاكيولر",
        description: "غرفة واسعة مع إطلالة بانورامية وتصميم فريد",
        pricePerNight: 250,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة بانورامية", "شرفة", "واي فاي", "ميني بار", "خدمة الغرف 24 ساعة"],
      },
      {
        id: "4-suite",
        name: "WOW Suite",
        nameAr: "جناح واو",
        description: "جناح فسيح بتصميم عصري مع غرفة معيشة منفصلة",
        pricePerNight: 380,
        maxGuests: 3,
        amenities: ["غرفة معيشة", "إطلالة بانورامية", "جاكوزي", "بوتلر خاص", "إفطار مجاني"],
      },
      {
        id: "4-royal",
        name: "Extreme WOW Suite",
        nameAr: "الجناح الرئاسي",
        description: "أفخم أجنحة الفندق مع مسبح خاص على السطح",
        pricePerNight: 750,
        maxGuests: 4,
        amenities: ["مسبح خاص", "غرفتين نوم", "مطبخ", "بوتلر خاص 24 ساعة", "ليموزين", "سبا خاص"],
      },
    ],
  },
  {
    id: "5",
    name: "Alila Jabal Akhdar",
    nameAr: "أليلا الجبل الأخضر",
    description: "منتجع بوتيكي فاخر على ارتفاع 2000 متر. يتميز بتصميمه المستدام وإطلالاته الخلابة على الوادي ومطعمه الراقي وبرامج العافية المميزة.",
    city: "نزوى",
    region: "الداخلية",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=800",
    ],
    amenities: ["سبا", "مسبح", "يوغا", "مطعم", "رحلات جبلية"],
    rating: 4.8,
    pricePerNight: 300,
    stars: 5,
    phone: "+968 2534 4200",
    roomOptions: [
      {
        id: "5-deluxe",
        name: "Mountain View Room",
        nameAr: "غرفة إطلالة الجبل",
        description: "غرفة أنيقة مع إطلالة على الجبل والوادي",
        pricePerNight: 300,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة جبل", "واي فاي", "تلفاز", "ميني بار"],
      },
      {
        id: "5-premier",
        name: "Canyon View Room",
        nameAr: "غرفة إطلالة الوادي",
        description: "غرفة واسعة مع إطلالة مباشرة على الوادي وشرفة خاصة",
        pricePerNight: 400,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة وادي", "شرفة خاصة", "واي فاي", "ميني بار", "خدمة الغرف 24 ساعة"],
      },
      {
        id: "5-suite",
        name: "Jabal Suite",
        nameAr: "جناح الجبل",
        description: "جناح فسيح مع غرفة معيشة منفصلة وإطلالة بانورامية",
        pricePerNight: 550,
        maxGuests: 3,
        amenities: ["غرفة معيشة", "إطلالة بانورامية", "جاكوزي", "بوتلر خاص", "إفطار مجاني"],
      },
      {
        id: "5-royal",
        name: "Alila Villa",
        nameAr: "فيلا أليلا",
        description: "فيلا خاصة مع مسبح خاص وإطلالة استثنائية",
        pricePerNight: 900,
        maxGuests: 4,
        amenities: ["مسبح خاص", "غرفتين نوم", "مطبخ", "بوتلر خاص 24 ساعة", "سيارة خاصة", "سبا خاص"],
      },
    ],
  },
  {
    id: "6",
    name: "Hilton Salalah Resort",
    nameAr: "هيلتون صلالة",
    description: "منتجع استوائي على شاطئ البحر العربي في صلالة. مثالي للاستمتاع بموسم الخريف مع حدائق خضراء ومسابح متعددة وشاطئ رملي طويل.",
    city: "صلالة",
    region: "ظفار",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=800",
    ],
    amenities: ["شاطئ", "مسابح", "سبا", "مطاعم", "رياضات مائية"],
    rating: 4.6,
    pricePerNight: 150,
    stars: 5,
    phone: "+968 2321 1234",
    roomOptions: [
      {
        id: "6-deluxe",
        name: "Garden View Room",
        nameAr: "غرفة إطلالة الحديقة",
        description: "غرفة مريحة مع إطلالة على الحدائق الاستوائية",
        pricePerNight: 150,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة حديقة", "واي فاي", "تلفاز", "ميني بار"],
      },
      {
        id: "6-premier",
        name: "Ocean View Room",
        nameAr: "غرفة إطلالة البحر",
        description: "غرفة واسعة مع إطلالة مباشرة على البحر العربي",
        pricePerNight: 200,
        maxGuests: 2,
        amenities: ["سرير كينج", "إطلالة بحر", "شرفة خاصة", "واي فاي", "ميني بار", "خدمة الغرف 24 ساعة"],
      },
      {
        id: "6-suite",
        name: "Executive Suite",
        nameAr: "جناح تنفيذي",
        description: "جناح فسيح مع غرفة معيشة منفصلة وإطلالة على البحر",
        pricePerNight: 320,
        maxGuests: 3,
        amenities: ["غرفة معيشة", "إطلالة بحر", "جاكوزي", "بوتلر خاص", "إفطار مجاني"],
      },
      {
        id: "6-royal",
        name: "Presidential Suite",
        nameAr: "الجناح الرئاسي",
        description: "أفخم أجنحة الفندق مع شاطئ خاص",
        pricePerNight: 650,
        maxGuests: 4,
        amenities: ["شاطئ خاص", "غرفتين نوم", "مطبخ", "بوتلر خاص 24 ساعة", "ليموزين", "سبا خاص"],
      },
    ],
  },
  {
    id: "8",
    name: "Crowne Plaza Muscat",
    nameAr: "كراون بلازا مسقط",
    description: "فندق أعمال راقٍ في قلب منطقة القرم التجارية. يوفر غرف واسعة ومرافق اجتماعات ومطاعم متنوعة مع سهولة الوصول لمراكز التسوق.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=800",
    ],
    amenities: ["مسبح", "نادي رياضي", "مطاعم", "قاعات اجتماعات", "واي فاي"],
    rating: 4.5,
    pricePerNight: 100,
    stars: 4,
    phone: "+968 2466 0660",
    roomOptions: [
      {
        id: "8-standard",
        name: "Standard Room",
        nameAr: "غرفة عادية",
        description: "غرفة مريحة مثالية لرجال الأعمال",
        pricePerNight: 100,
        maxGuests: 2,
        amenities: ["سرير كينج", "مكتب عمل", "واي فاي", "تلفاز", "ميني بار"],
      },
      {
        id: "8-deluxe",
        name: "Deluxe Room",
        nameAr: "غرفة ديلوكس",
        description: "غرفة واسعة مع منطقة جلوس وإطلالة على المدينة",
        pricePerNight: 140,
        maxGuests: 2,
        amenities: ["سرير كينج", "منطقة جلوس", "إطلالة مدينة", "واي فاي", "ميني بار", "خدمة الغرف 24 ساعة"],
      },
      {
        id: "8-suite",
        name: "Executive Suite",
        nameAr: "جناح تنفيذي",
        description: "جناح فسيح مع غرفة معيشة منفصلة ومرافق أعمال",
        pricePerNight: 220,
        maxGuests: 3,
        amenities: ["غرفة معيشة", "مكتب عمل", "غرفة اجتماعات صغيرة", "إفطار مجاني", "صالة تنفيذية"],
      },
      {
        id: "8-royal",
        name: "Presidential Suite",
        nameAr: "الجناح الرئاسي",
        description: "أفخم أجنحة الفندق مع خدمات VIP",
        pricePerNight: 450,
        maxGuests: 4,
        amenities: ["غرفتين نوم", "غرفة معيشة", "مطبخ", "بوتلر خاص", "ليموزين", "صالة VIP"],
      },
    ],
  },
];
