import type { Restaurant } from "@shared/schema";
import alburjCafeImg from "@/assets/alburj-cafe.png";
import lagunaCafeImg from "@/assets/laguna-cafe.png";
import baitAlmadghootImg from "@/assets/bait-almadghoot.png";
import musandamFanrImg from "@/assets/musandam-fanr.png";

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "The Beach Restaurant",
    nameAr: "مطعم الشاطئ",
    description: "مطعم فاخر على شاطئ القرم يقدم أشهى المأكولات البحرية الطازجة مع إطلالة ساحرة على البحر. تجربة طعام استثنائية تحت النجوم.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800",
    cuisine: "مأكولات بحرية",
    priceRange: "luxury",
    rating: 4.8,
    features: ["إطلالة بحرية", "جلسات خارجية", "واي فاي", "مواقف سيارات"],
  },
  {
    id: "2",
    name: "Bait Al Luban",
    nameAr: "بيت اللبان",
    description: "مطعم عُماني أصيل في قلب مطرح يقدم أطباقاً تقليدية بنكهة عُمانية خالصة. جرب الشوا والمقبوس في أجواء تراثية فريدة.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=800",
    cuisine: "عُماني تقليدي",
    priceRange: "moderate",
    rating: 4.7,
    features: ["طعام تقليدي", "أجواء تراثية", "خدمة ممتازة", "حلويات عُمانية"],
  },
  {
    id: "3",
    name: "Kargeen Caffe",
    nameAr: "كافيه كارجين",
    description: "مقهى ومطعم شهير بأجوائه العربية الساحرة وحديقته الخضراء. يقدم مزيجاً من المأكولات العربية والعالمية مع الشيشة.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?q=80&w=800",
    cuisine: "عربي متنوع",
    priceRange: "moderate",
    rating: 4.6,
    features: ["حديقة خضراء", "شيشة", "أجواء عربية", "مفتوح للعائلات"],
  },
  {
    id: "4",
    name: "Al Angham",
    nameAr: "الأنغام",
    description: "مطعم راقٍ في دار الأوبرا السلطانية يقدم تجربة طعام فاخرة مع المأكولات العُمانية المعاصرة في أجواء فنية راقية.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=800",
    cuisine: "عُماني معاصر",
    priceRange: "luxury",
    rating: 4.9,
    features: ["إطلالة على الأوبرا", "طعام فاخر", "خدمة VIP", "موسيقى حية"],
  },
  {
    id: "5",
    name: "Bin Ateeq",
    nameAr: "بن عتيق",
    description: "سلسلة مطاعم عُمانية شعبية تقدم أشهر الأطباق المحلية بأسعار معقولة. المكان المثالي لتذوق الطعام العُماني الأصيل.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=800",
    cuisine: "عُماني شعبي",
    priceRange: "budget",
    rating: 4.5,
    features: ["أسعار معقولة", "وجبات سريعة", "توصيل", "فروع متعددة"],
  },
  {
    id: "6",
    name: "Ubhar Restaurant",
    nameAr: "مطعم أوبهار",
    description: "مطعم بحري فاخر يقدم أجود أنواع الأسماك والمأكولات البحرية الطازجة مع إطلالة خلابة على البحر.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?q=80&w=800",
    cuisine: "مأكولات بحرية",
    priceRange: "expensive",
    rating: 4.7,
    features: ["سمك طازج", "إطلالة بحرية", "خدمة راقية", "حجز مسبق"],
  },
  {
    id: "7",
    name: "Al Mandoos",
    nameAr: "المندوس",
    description: "مطعم في فندق الريتز كارلتون يقدم رحلة طهي عبر المطبخ العُماني التقليدي في أجواء فخمة وتصميم تراثي أنيق.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=800",
    cuisine: "عُماني فاخر",
    priceRange: "luxury",
    rating: 4.8,
    features: ["فندق 5 نجوم", "تصميم تراثي", "قائمة تذوق", "خدمة استثنائية"],
  },
  {
    id: "8",
    name: "Salalah Restaurant",
    nameAr: "مطعم صلالة",
    description: "مطعم في قلب صلالة يقدم أطباق ظفارية أصيلة وأسماك البحر العربي الطازجة. تجربة طعام محلية لا تُنسى.",
    city: "صلالة",
    region: "ظفار",
    image: "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?q=80&w=800",
    cuisine: "ظفاري",
    priceRange: "moderate",
    rating: 4.6,
    features: ["مطبخ ظفاري", "أسماك طازجة", "أجواء عائلية", "أسعار معقولة"],
  },
  {
    id: "9",
    name: "Al Burj Cafe",
    nameAr: "قهوة البرج",
    description: "يُعد قهوة البرج من الوجهات المميزة التي تجمع بين عبق الماضي والجمال المعماري، حيث يقع في قلب المعالم التاريخية. يشتهر بتقديم القهوة العمانية الأصيلة والوجبات الخفيفة والحلويات في أجواء تراثية ساحرة، مما يجعله محطة رائعة للزوار الراغبين في الاستراحة أثناء استكشاف المعالم التاريخية المحيطة.",
    city: "ولاية الرستاق",
    region: "محافظة جنوب الباطنة",
    image: alburjCafeImg,
    cuisine: "مقهى تراثي",
    priceRange: "moderate",
    rating: 4.7,
    features: ["قهوة عمانية", "حلويات", "أجواء تراثية", "إطلالة تاريخية"],
    mapUrl: "https://maps.app.goo.gl/XhPr7YVE4UKRUvG26",
  },
  {
    id: "10",
    name: "Laguna",
    nameAr: "لاجونا",
    description: "يُعد لاجونا وجهة عصرية وشهيرة، ويُعرف بكونه مطعماً ومقهى يقدم تشكيلة متنوعة من المأكولات والمشروبات، بما في ذلك الحلويات والوجبات الخفيفة والقهوة المختصة. يتميز المكان بجلساته المريحة وتصميمه الجذاب، مما يجعله مكاناً مفضلاً للقاءات الأصدقاء والعائلات، خاصة في الفترة المسائية.",
    city: "ولاية السيب",
    region: "محافظة مسقط",
    image: lagunaCafeImg,
    cuisine: "مقهى عصري",
    priceRange: "moderate",
    rating: 4.6,
    features: ["قهوة مختصة", "حلويات", "جلسات مريحة", "تصميم عصري"],
    mapUrl: "https://maps.app.goo.gl/4FfHKFAkuqNZp16T6",
  },
  {
    id: "11",
    name: "Bait Al Madhgoot",
    nameAr: "بيت المضغوط",
    description: "يعتبر مطعم بيت المضغوط في البريمي وجهة مفضلة لمحبي الأكلات الشعبية، حيث يتخصص في تقديم طبق \"المضغوط\" بطعمه الأصيل. يتميز المطعم بجودة مكوناته من اللحوم والأرز واستخدام التوابل التقليدية التي تمنحه مذاقاً خاصاً. كما يشتهر المطعم بنظافته وخدمته السريعة، مما يجعله خياراً ممتازاً للوجبات العائلية أو الولائم.",
    city: "ولاية البريمي",
    region: "محافظة البريمي",
    image: baitAlmadghootImg,
    cuisine: "عُماني شعبي",
    priceRange: "budget",
    rating: 4.5,
    features: ["مضغوط أصيل", "خدمة سريعة", "مناسب للعائلات", "نظافة عالية"],
    mapUrl: "https://maps.app.goo.gl/NCRTT4jLr9gkwPgw7",
  },
  {
    id: "12",
    name: "Musandam Fanr Restaurant",
    nameAr: "مطعم فنر مسندم",
    description: "يُعد مطعم فنر مسندم من المطاعم المعروفة في مدينة خصب، ويشتهر بتقديم تشكيلة متنوعة من المأكولات، وخاصة الأطباق البحرية الطازجة التي تشتهر بها المنطقة، بالإضافة إلى الأطباق العربية والآسيوية. يتميز المطعم بموقعه القريب من الميناء والخدمات السياحية، ويحظى بتقييمات جيدة لنظافته وجودة طعمه، مما يجعله وجهة مفضلة للسياح الراغبين في تجربة المذاق المحلي بعد جولات القوارب في أخوار مسندم.",
    city: "ولاية خصب",
    region: "محافظة مسندم",
    image: musandamFanrImg,
    cuisine: "مأكولات بحرية",
    priceRange: "moderate",
    rating: 4.5,
    features: ["أسماك طازجة", "قريب من الميناء", "أطباق آسيوية", "نظافة عالية"],
    mapUrl: "https://maps.app.goo.gl/qAJm51We5uRj9oeo8",
  },
];
