import type { Taxi } from "@shared/schema";

export const taxis: Taxi[] = [
  {
    id: "1",
    name: "Mwasalat",
    nameAr: "مواصلات",
    description: "شركة النقل الوطنية في سلطنة عُمان. توفر خدمات تاكسي موثوقة ومريحة بأسعار معقولة مع سائقين محترفين.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=800",
    vehicleType: "سيدان",
    pricePerKm: 0.3,
    rating: 4.5,
    features: ["تطبيق جوال", "دفع إلكتروني", "تتبع الرحلة", "سائقين مرخصين"],
    phone: "+968 24 777 888",
  },
  {
    id: "2",
    name: "Oman Taxi",
    nameAr: "تاكسي عُمان",
    description: "خدمة تاكسي متميزة تغطي جميع مناطق السلطنة. سيارات حديثة ومكيفة مع خدمة على مدار الساعة.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1511452885600-a3d2c9148a31?q=80&w=800",
    vehicleType: "سيدان فاخر",
    pricePerKm: 0.4,
    rating: 4.6,
    features: ["24/7", "واي فاي", "مياه مجانية", "سيارات جديدة"],
    phone: "+968 24 600 600",
  },
  {
    id: "3",
    name: "Airport Taxi",
    nameAr: "تاكسي المطار",
    description: "خدمة متخصصة في التوصيل من وإلى مطار مسقط الدولي. حجز مسبق متاح مع استقبال من البوابة.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1559829604-8c2cc92e4fb8?q=80&w=800",
    vehicleType: "SUV",
    pricePerKm: 0.5,
    rating: 4.7,
    features: ["استقبال من المطار", "مساعدة بالأمتعة", "حجز مسبق", "لوحة باسمك"],
    phone: "+968 24 519 219",
  },
  {
    id: "4",
    name: "Luxury Limousine",
    nameAr: "ليموزين فاخر",
    description: "خدمة ليموزين فاخرة للمناسبات الخاصة ورجال الأعمال. سيارات فارهة مع سائقين محترفين بزي رسمي.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=800",
    vehicleType: "ليموزين",
    pricePerKm: 1.0,
    rating: 4.9,
    features: ["سيارات فارهة", "سائق بزي رسمي", "مشروبات", "خصوصية تامة"],
    phone: "+968 24 700 700",
  },
  {
    id: "5",
    name: "Safari Tours",
    nameAr: "رحلات سفاري",
    description: "سيارات دفع رباعي لرحلات الصحراء والجبال. مثالية لاستكشاف الأودية والكثبان الرملية مع سائقين خبراء.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800",
    vehicleType: "4x4",
    pricePerKm: 0.6,
    rating: 4.8,
    features: ["دفع رباعي", "رحلات صحراوية", "سائق خبير", "معدات تخييم"],
    phone: "+968 24 800 800",
  },
  {
    id: "6",
    name: "Family Van",
    nameAr: "فان عائلي",
    description: "سيارات فان واسعة للعائلات والمجموعات. تتسع حتى 7 ركاب مع مساحة كافية للأمتعة.",
    city: "مسقط",
    region: "مسقط",
    image: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=800",
    vehicleType: "فان",
    pricePerKm: 0.45,
    rating: 4.5,
    features: ["7 مقاعد", "مساحة أمتعة", "مقاعد أطفال", "تكييف قوي"],
    phone: "+968 24 555 555",
  },
  {
    id: "7",
    name: "Salalah Taxi",
    nameAr: "تاكسي صلالة",
    description: "خدمة تاكسي محلية في صلالة تغطي المدينة والمناطق السياحية المحيطة. خبرة في المنطقة.",
    city: "صلالة",
    region: "ظفار",
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?q=80&w=800",
    vehicleType: "سيدان",
    pricePerKm: 0.35,
    rating: 4.4,
    features: ["معرفة محلية", "جولات سياحية", "أسعار معقولة", "لغات متعددة"],
    phone: "+968 23 290 290",
  },
  {
    id: "8",
    name: "Nizwa Transport",
    nameAr: "نقل نزوى",
    description: "خدمة نقل في نزوى والمناطق الداخلية. مثالية لزيارة القلاع والأسواق التقليدية والجبل الأخضر.",
    city: "نزوى",
    region: "الداخلية",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800",
    vehicleType: "SUV",
    pricePerKm: 0.4,
    rating: 4.6,
    features: ["جولات ثقافية", "رحلات الجبل", "سائق مرشد", "مرونة في المواعيد"],
    phone: "+968 25 411 411",
  },
];
